#! /bin/bash

bspc monitor -d "Navegador geral" Mídia IDE Terminais Configurações Emails "Navegador pessoal"

bspc config border_width         0
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
